
@echo off

set shelldir=%~dp0
cd %shelldir%

echo .......
call link_game.bat bazhang
echo .......
call link_game.bat guanpai
echo .......
call link_game.bat shuangkou
echo .......
call link_game.bat tonglu_mj
echo .......